import { ChevronDown, ChevronUp, Lock, MapPin, MessageCircle, Snowflake, Star } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ROUTES } from '../../../constants/routes.js'
import mockProviders from '../../../data/mockProviders.js'
function AvailableProvidersSection() { const [open, setOpen] = useState(true); return <section className="bg-[#eff4ff] py-16"><div className="mx-auto max-w-6xl px-4 lg:px-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Transparence totale</p><h2 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Techniciens en service aujourd’hui</h2></div><div className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-xs shadow-sm"><Lock size={16} className="text-emerald-700" /> WhatsApp protégé déblocable pour <strong className="text-blue-700">100 FCFA / 24h</strong></div></div>
  <div className="overflow-hidden rounded-2xl bg-white shadow-md"><button type="button" className="flex w-full items-center justify-between gap-3 p-5 text-left hover:bg-slate-50" onClick={() => setOpen((v) => !v)} aria-expanded={open} aria-controls="provider-list"><span className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-xl bg-sky-100 text-sky-700"><Snowflake /></span><span><strong className="block">Climatisation & Froid <small className="ml-2 rounded-full bg-emerald-100 px-2 py-1 text-[10px] text-emerald-800">4 disponibles maintenant</small></strong><small className="text-slate-500">Maintenance générale, fuites de fréon, installations neuves</small></span></span>{open ? <ChevronUp className="text-blue-700" /> : <ChevronDown />}</button>
  {open && <div id="provider-list" className="space-y-2 px-4 pb-5">{mockProviders.map((provider) => <article key={provider.id} className="flex flex-col justify-between gap-4 rounded-xl bg-[#f5f8ff] p-4 sm:flex-row sm:items-center"><Link to={`/prestataires/${provider.id}`} className="flex min-w-0 items-center gap-3"><span className="relative grid size-12 shrink-0 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">{provider.name.split(' ').map((word) => word[0]).join('')}<i className={`absolute bottom-0 right-0 size-3 rounded-full ring-2 ring-white ${provider.available ? 'bg-green-500' : 'bg-amber-400'}`} /></span><span className="min-w-0"><strong className="block truncate">{provider.name} <span className="text-emerald-700">✓</span></strong><span className="flex flex-wrap items-center gap-x-2 text-[11px] text-slate-500"><span className="inline-flex items-center gap-1"><MapPin size={12} />{provider.city}</span><b className="text-emerald-700">Arrivée estimée : {provider.eta}</b><span className="inline-flex items-center gap-1"><Star size={11} />{provider.rating} ({provider.jobs})</span></span></span></Link><div className="flex items-center justify-end gap-2"><span className="hidden items-center gap-1 rounded bg-blue-50 px-2 py-1 text-[10px] text-slate-500 lg:inline-flex"><Lock size={12} />Contact protégé</span><Link to={`/paiement/${provider.id}`} className="inline-flex items-center gap-2 rounded-lg bg-[#006056] px-3 py-2 text-xs font-bold text-white hover:bg-[#007b6e]"><MessageCircle size={16} />Débloquer WhatsApp <span className="rounded bg-black/20 px-1.5 py-1">100 F</span></Link></div></article>)}</div>}</div>
  <div className="mt-3 grid gap-3">{['Électricité Bâtiment & Dépannage','Plomberie & Raccordements'].map((name) => <Link key={name} to={`${ROUTES.providers}?service=${encodeURIComponent(name)}`} className="flex items-center justify-between rounded-xl bg-white p-5 shadow-sm"><strong>{name}</strong><span className="inline-flex items-center gap-2 text-xs text-slate-500">Voir les artisans <ChevronDown size={18} /></span></Link>)}</div></div></section> }
export default AvailableProvidersSection
