import { ArrowLeft, ChevronRight, LockKeyhole } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ROUTES } from '../../../constants/routes.js'
import mockProviders from '../../../data/mockProviders.js'
import MobileMoneyForm from '../components/MobileMoneyForm.jsx'
import PaymentSecurityNotice from '../components/PaymentSecurityNotice.jsx'
import PaymentSummary from '../components/PaymentSummary.jsx'
import initializeDemoPayment from '../services/paymentDemo.js'
function PaymentPage(){const {providerId}=useParams();const provider=mockProviders.find((item)=>item.id===providerId);const [processing,setProcessing]=useState(false);const navigate=useNavigate();const submit=async({method,phone})=>{if(processing)return;setProcessing(true);const result=await initializeDemoPayment({providerId,method,phone});navigate(`/paiement/statut/${result.reference}`,{state:result})};if(!provider)return <section className="mx-auto max-w-2xl px-4 py-20 text-center"><h1 className="text-3xl font-bold">Prestataire introuvable</h1><p className="mt-3 text-slate-600">Impossible de préparer un paiement pour cet identifiant.</p><Link to={ROUTES.providers} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white"><ArrowLeft size={18}/>Retour aux prestataires</Link></section>;return <section className="py-10"><div className="mx-auto max-w-6xl px-4 lg:px-8"><nav aria-label="Fil d’Ariane" className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><Link to={ROUTES.home}>Accueil</Link><ChevronRight size={13}/><Link to={ROUTES.providers}>Prestataires</Link><ChevronRight size={13}/><Link to={`/prestataires/${provider.id}`}>{provider.name}</Link><ChevronRight size={13}/><span className="font-bold text-slate-800">Paiement sécurisé</span></nav><div className="mt-8"><p className="inline-flex items-center gap-2 rounded-full bg-blue-100 px-3 py-2 text-[10px] font-bold uppercase text-blue-700"><LockKeyhole size={13}/>Pass accès direct 24h</p><h1 className="mt-3 text-3xl font-extrabold sm:text-4xl">Déblocage sécurisé des coordonnées</h1><p className="mt-2 text-sm text-slate-600">Réglez le micropaiement unique de 100 FCFA. Aucun contact n’est inclus dans cette page.</p></div><div className="mt-8 grid items-start gap-6 lg:grid-cols-12"><div className="space-y-5 lg:col-span-5"><PaymentSummary provider={provider}/><PaymentSecurityNotice/></div><div className="lg:col-span-7"><MobileMoneyForm onSubmit={submit} processing={processing}/></div></div><div className="mt-10 rounded-2xl bg-blue-100 p-5"><p className="text-xs font-bold uppercase text-blue-700">Mode test actif</p><p className="mt-1 text-sm text-slate-600">La démonstration s’arrête volontairement à l’état « en attente ». Seul un futur backend pourra confirmer, échouer ou annuler la transaction.</p></div></div></section>}
export default PaymentPage
